openapi: 3.1.0

info:
  $ref: ./info.yaml

servers:
  $ref: ./servers.yaml

tags:
  $ref: ./tags.yaml

paths:
  /api/status:
    $ref: ./paths/api_status.yaml

components:
  schemas:
    $ref: ./components/schemas.yaml
  responses:
    $ref: ./components/responses.yaml
